{{- if .Values.etherpad.scheduled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-etherpad-scale-role-binding
subjects:
  - namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
    name: {{ .Release.Name }}-etherpad-startstop-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-etherpad-scale-role
{{- end }}
