{{- if .Values.etherpad.scheduled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-etherpad-scale-role
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: [ "get" ]
  - apiGroups:
      - apps
    resources:
      - deployments/scale
    verbs: [ "patch" ]
{{- end }}
