apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-etherpad
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: etherpad
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: etherpad
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etherpad
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: etherpad
          image: "etherpad/etherpad:1.8.18"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9001
              protocol: TCP
          resources:
            {{- toYaml .Values.etherpad.resources | nindent 12 }}
