apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-etherpad
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: etherpad
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 9001
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: etherpad
    app.kubernetes.io/instance: {{ .Release.Name }}
