{{- $hostname := default (index .Values "jitsi-meet" "jvb" "publicIP") .Values.fqdn }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jitsi-websecure
spec:
  entryPoints:
    {{- if eq (int .Values.port) 443 }}
    - websecure
    {{- else }}
    - jitsi-meet
    {{- end }}
  routes:
    - kind: Rule
      match: Host(`{{ $hostname }}`) && PathPrefix(`/`)
      services:
        - name: {{ .Release.Name }}-jitsi-meet-web
          port: 80
  {{- if .Values.certResolver }}
  tls:
    certResolver: {{ .Values.certResolver }}
  {{- else }}
  tls: {}
  {{- end }}

{{- if eq (int .Values.port) 443 }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jitsi-web
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ $hostname }}`) && PathPrefix(`/`)
      middlewares:
        - name: jitsi-web-redirectscheme
      services:
        - name: {{ .Release.Name }}-jitsi-meet-web
          port: 80
{{- end }}
