apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: redir
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      middlewares:
      - name: any-redirectregex
      services:
        - name: {{ .Release.Name }}-jitsi-meet-web
          port: 80
