apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-ingressroutetcp-prosody
spec:
  entryPoints:
  - xmpp-{{ .Release.Name }}
  routes:
  - match: HostSNI(`*`)
    services:
    - name: {{ .Release.Name }}-prosody
      port: 5222
