---
certResolver: le-staging

fqdn: ""

port: 443

etherpad:
  scheduled: false
  schedules:
    start: ""
    stop: ""

jitsi-meet:
  publicURL: ""

  tz: Asia/Shanghai

  web:
    ingress:
      enabled: false

  jicofo:
    livenessProbe:
      failureThreshold: 30
      periodSeconds: 10
    readinessProbe:
      failureThreshold: 30
      periodSeconds: 10

  jvb:
    service:
      type: NodePort
    UDPPort: 30000

    livenessProbe:
      failureThreshold: 30
      periodSeconds: 10
    readinessProbe:
      failureThreshold: 30
      periodSeconds: 10

    websockets:
      enabled: true

    publicIP: ""

  etherpad:
    enabled: true
    replicaCount: 1
